[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]

  NODE_VERSION = "20"

# Scheduled Functions
[[functions]]
  name = "scheduled-posts-sync"
  schedule = "0 0 * * *"  # Run daily at midnight UTC
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"